# Generated by Django 5.2.5 on 2025-10-18 12:23

import student.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', student.models.CustomUserManager()),
            ],
        ),
    ]
