# Generated by Django 5.2.5 on 2025-09-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_address_student_fathername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mothername',
            new_name='father_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fathername',
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default='Not Provided', max_length=200),
        ),
    ]
