# Generated by Django 5.2.5 on 2025-10-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='day',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='routine',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='routines/'),
        ),
        migrations.AddField(
            model_name='routine',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
