# Generated by Django 5.2.5 on 2025-09-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_mothername_student_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
